import { dbManager } from './database';
import { Company, Equipment, Inspector, InspectionApply, Schedule, HydroTest, ValveTest, Defect, Report, Certificate } from './schema';

const companies: Omit<Company, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: '东方化工有限公司',
    unifiedSocialCreditCode: '91110000100000001A',
    legalPerson: '张三',
    contactPerson: '李四',
    contactPhone: '13800138001',
    address: '北京市朝阳区化工路100号',
    province: '北京市',
    city: '北京市',
    district: '朝阳区',
    industryType: '化工',
    enterpriseScale: '大型',
    establishmentDate: '2005-03-15',
    businessScope: '化工产品生产、销售',
    remark: '重点监控企业',
  },
  {
    name: '华南制药股份有限公司',
    unifiedSocialCreditCode: '91440000200000002B',
    legalPerson: '王五',
    contactPerson: '赵六',
    contactPhone: '13800138002',
    address: '广州市天河区制药工业园88号',
    province: '广东省',
    city: '广州市',
    district: '天河区',
    industryType: '制药',
    enterpriseScale: '大型',
    establishmentDate: '1998-07-20',
    businessScope: '药品生产、研发',
  },
  {
    name: '北方钢铁集团',
    unifiedSocialCreditCode: '91310000300000003C',
    legalPerson: '钱七',
    contactPerson: '孙八',
    contactPhone: '13800138003',
    address: '上海市宝山区钢铁大道666号',
    province: '上海市',
    city: '上海市',
    district: '宝山区',
    industryType: '冶金',
    enterpriseScale: '特大型',
    establishmentDate: '1985-10-01',
    businessScope: '钢铁冶炼、加工',
    remark: 'A级特种设备使用单位',
  },
  {
    name: '西湖食品有限公司',
    unifiedSocialCreditCode: '91330000400000004D',
    legalPerson: '周九',
    contactPerson: '吴十',
    contactPhone: '13800138004',
    address: '杭州市西湖区食品街55号',
    province: '浙江省',
    city: '杭州市',
    district: '西湖区',
    industryType: '食品',
    enterpriseScale: '中型',
    establishmentDate: '2010-06-18',
    businessScope: '食品加工、销售',
  },
  {
    name: '锦江纺织厂',
    unifiedSocialCreditCode: '91510000500000005E',
    legalPerson: '郑十一',
    contactPerson: '冯十二',
    contactPhone: '13800138005',
    address: '成都市锦江区纺织路200号',
    province: '四川省',
    city: '成都市',
    district: '锦江区',
    industryType: '纺织',
    enterpriseScale: '中型',
    establishmentDate: '2008-02-28',
    businessScope: '纺织品生产、印染',
  },
];

const inspectors: Omit<Inspector, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    employeeNo: 'INS2023001',
    name: '陈检验',
    gender: 'male',
    idCard: '110101198501011234',
    phone: '13900139001',
    email: 'chenjy@inspection.gov.cn',
    department: '锅炉检验一室',
    position: '主任检验师',
    qualificationLevel: '高级检验师',
    qualificationCertificateNo: 'GL20180001',
    qualificationExpiryDate: '2028-12-31',
    inspectionScope: '电站锅炉、工业锅炉',
    hireDate: '2010-05-01',
    status: 'active',
  },
  {
    employeeNo: 'INS2023002',
    name: '刘检测',
    gender: 'female',
    idCard: '110102198602022345',
    phone: '13900139002',
    email: 'liujc@inspection.gov.cn',
    department: '锅炉检验一室',
    position: '检验师',
    qualificationLevel: '中级检验师',
    qualificationCertificateNo: 'GL20190002',
    qualificationExpiryDate: '2029-06-30',
    inspectionScope: '工业锅炉、热水锅炉',
    hireDate: '2012-08-15',
    status: 'active',
  },
  {
    employeeNo: 'INS2023003',
    name: '张探伤',
    gender: 'male',
    idCard: '110103198703033456',
    phone: '13900139003',
    email: 'zhangts@inspection.gov.cn',
    department: '无损检测室',
    position: '无损检测师',
    qualificationLevel: '高级无损检测师',
    qualificationCertificateNo: 'WS20170003',
    qualificationExpiryDate: '2027-09-15',
    inspectionScope: 'UT、RT、MT、PT无损检测',
    hireDate: '2008-03-20',
    status: 'active',
  },
  {
    employeeNo: 'INS2023004',
    name: '王水压',
    gender: 'male',
    idCard: '110104198804044567',
    phone: '13900139004',
    email: 'wangsy@inspection.gov.cn',
    department: '锅炉检验二室',
    position: '检验师',
    qualificationLevel: '中级检验师',
    qualificationCertificateNo: 'GL20200004',
    qualificationExpiryDate: '2030-03-20',
    inspectionScope: '有机热载体锅炉、余热锅炉',
    hireDate: '2015-01-10',
    status: 'active',
  },
  {
    employeeNo: 'INS2023005',
    name: '李安全',
    gender: 'female',
    idCard: '110105199005055678',
    phone: '13900139005',
    email: 'liaq@inspection.gov.cn',
    department: '审核室',
    position: '报告审核师',
    qualificationLevel: '高级检验师',
    qualificationCertificateNo: 'GL20160005',
    qualificationExpiryDate: '2026-11-30',
    inspectionScope: '报告审核、技术评审',
    hireDate: '2006-07-01',
    status: 'active',
    remark: '技术负责人',
  },
];

const createEquipments = (companyIds: number[]): Omit<Equipment, 'id' | 'createdAt' | 'updatedAt'>[] => [
  {
    companyId: companyIds[0],
    equipmentCode: 'GL-2024-0001',
    equipmentName: '燃煤蒸汽锅炉',
    equipmentType: '工业锅炉',
    modelSpecification: 'DZL10-1.25-AII',
    designPressure: 1.25,
    designTemperature: 194,
    workingPressure: 1.0,
    workingTemperature: 184,
    volume: 15.8,
    diameter: 1800,
    wallThickness: 16,
    material: 'Q245R',
    manufactureDate: '2018-05-20',
    commissioningDate: '2018-08-15',
    installationLocation: '一号车间锅炉房',
    useRegistrationCode: '锅京朝字第0001号',
    nextInspectionDate: '2026-08-15',
    lastInspectionDate: '2024-08-10',
    equipmentStatus: 'normal',
    remark: '主要生产用汽',
  },
  {
    companyId: companyIds[0],
    equipmentCode: 'GL-2024-0002',
    equipmentName: '燃气热水锅炉',
    equipmentType: '热水锅炉',
    modelSpecification: 'WNS4.2-1.0/115/70-Y(Q)',
    designPressure: 1.0,
    designTemperature: 150,
    workingPressure: 0.8,
    workingTemperature: 115,
    volume: 8.5,
    diameter: 1500,
    wallThickness: 14,
    material: 'Q245R',
    manufactureDate: '2020-03-10',
    commissioningDate: '2020-05-01',
    installationLocation: '办公楼地下室锅炉房',
    useRegistrationCode: '锅京朝字第0002号',
    nextInspectionDate: '2025-05-01',
    lastInspectionDate: '2023-04-20',
    equipmentStatus: 'normal',
  },
  {
    companyId: companyIds[1],
    equipmentCode: 'GL-2024-0003',
    equipmentName: '电加热蒸汽锅炉',
    equipmentType: '工业锅炉',
    modelSpecification: 'WDR2-1.0',
    designPressure: 1.0,
    designTemperature: 184,
    workingPressure: 0.9,
    workingTemperature: 179,
    volume: 4.2,
    diameter: 1200,
    wallThickness: 12,
    material: 'Q245R',
    manufactureDate: '2021-06-15',
    commissioningDate: '2021-08-01',
    installationLocation: '制剂车间锅炉房',
    useRegistrationCode: '锅粤穗字第0003号',
    nextInspectionDate: '2026-08-01',
    lastInspectionDate: '2024-07-15',
    equipmentStatus: 'normal',
    remark: 'GMP车间专用',
  },
  {
    companyId: companyIds[2],
    equipmentCode: 'GL-2024-0004',
    equipmentName: '电站煤粉锅炉',
    equipmentType: '电站锅炉',
    modelSpecification: 'HG-670/13.7-YM10',
    designPressure: 13.7,
    designTemperature: 540,
    workingPressure: 13.2,
    workingTemperature: 535,
    volume: 520,
    diameter: 3800,
    wallThickness: 90,
    material: '12Cr1MoVG',
    manufactureDate: '2015-11-08',
    commissioningDate: '2016-03-20',
    installationLocation: '自备电厂一号机组',
    useRegistrationCode: '锅沪宝字第0004号',
    nextInspectionDate: '2027-03-20',
    lastInspectionDate: '2024-02-28',
    equipmentStatus: 'normal',
    remark: '60MW机组配套',
  },
  {
    companyId: companyIds[2],
    equipmentCode: 'GL-2024-0005',
    equipmentName: '余热回收锅炉',
    equipmentType: '余热锅炉',
    modelSpecification: 'QC60/450-20-4.0',
    designPressure: 4.0,
    designTemperature: 450,
    workingPressure: 3.8,
    workingTemperature: 435,
    volume: 35,
    diameter: 2200,
    wallThickness: 20,
    material: '15CrMoG',
    manufactureDate: '2019-08-25',
    commissioningDate: '2019-12-01',
    installationLocation: '炼钢车间烟气系统',
    useRegistrationCode: '锅沪宝字第0005号',
    nextInspectionDate: '2026-12-01',
    lastInspectionDate: '2023-11-15',
    equipmentStatus: 'normal',
  },
  {
    companyId: companyIds[3],
    equipmentCode: 'GL-2024-0006',
    equipmentName: '燃油蒸汽锅炉',
    equipmentType: '工业锅炉',
    modelSpecification: 'WNS6-1.25-Y',
    designPressure: 1.25,
    designTemperature: 194,
    workingPressure: 1.1,
    workingTemperature: 188,
    volume: 10.5,
    diameter: 1600,
    wallThickness: 16,
    material: 'Q245R',
    manufactureDate: '2017-04-12',
    commissioningDate: '2017-06-20',
    installationLocation: '蒸煮车间锅炉房',
    useRegistrationCode: '锅浙杭字第0006号',
    nextInspectionDate: '2025-06-20',
    lastInspectionDate: '2024-06-10',
    equipmentStatus: 'maintenance',
    remark: '计划下月进行内部检验',
  },
  {
    companyId: companyIds[4],
    equipmentCode: 'GL-2024-0007',
    equipmentName: '导热油炉',
    equipmentType: '有机热载体锅炉',
    modelSpecification: 'YYW-3500Y(Q)',
    designPressure: 1.0,
    designTemperature: 320,
    workingPressure: 0.6,
    workingTemperature: 300,
    volume: 12,
    diameter: 1800,
    wallThickness: 14,
    material: 'Q245R',
    manufactureDate: '2019-12-05',
    commissioningDate: '2020-02-18',
    installationLocation: '印染车间锅炉房',
    useRegistrationCode: '锅川成字第0007号',
    nextInspectionDate: '2026-02-18',
    lastInspectionDate: '2024-01-25',
    equipmentStatus: 'normal',
    remark: '染色工艺用热',
  },
];

const createInspectionApplies = (companyIds: number[], equipmentIds: number[]): Omit<InspectionApply, 'id' | 'createdAt' | 'updatedAt'>[] => [
  {
    applyNo: 'BJ202506001',
    companyId: companyIds[0],
    equipmentId: equipmentIds[0],
    inspectionType: 'periodic',
    inspectionNature: 'regular',
    applyDate: '2025-06-01',
    applyReason: '年度定期检验到期',
    applicant: '李四',
    applicantPhone: '13800138001',
    status: 'completed',
    approverId: 5,
    approvalOpinion: '同意安排检验',
    approvalDate: '2025-06-02',
  },
  {
    applyNo: 'BJ202506002',
    companyId: companyIds[0],
    equipmentId: equipmentIds[1],
    inspectionType: 'periodic',
    inspectionNature: 'regular',
    applyDate: '2025-06-05',
    applyReason: '年度定期检验到期',
    applicant: '李四',
    applicantPhone: '13800138001',
    status: 'approved',
    approverId: 5,
    approvalOpinion: '同意，安排在下半月',
    approvalDate: '2025-06-06',
  },
  {
    applyNo: 'BJ202506003',
    companyId: companyIds[1],
    equipmentId: equipmentIds[2],
    inspectionType: 'periodic',
    inspectionNature: 'regular',
    applyDate: '2025-06-10',
    applyReason: 'GMP认证前检验',
    applicant: '赵六',
    applicantPhone: '13800138002',
    status: 'scheduled',
    approverId: 5,
    approvalOpinion: '同意安排',
    approvalDate: '2025-06-11',
  },
  {
    applyNo: 'BJ202506004',
    companyId: companyIds[2],
    equipmentId: equipmentIds[4],
    inspectionType: 'supervision',
    inspectionNature: 'special',
    applyDate: '2025-06-12',
    applyReason: '设备运行参数异常，申请专项监督检验',
    applicant: '孙八',
    applicantPhone: '13800138003',
    status: 'inspecting',
    approverId: 5,
    approvalOpinion: '紧急安排，重点检查过热器',
    approvalDate: '2025-06-12',
  },
  {
    applyNo: 'BJ202506005',
    companyId: companyIds[3],
    equipmentId: equipmentIds[5],
    inspectionType: 'reinspection',
    inspectionNature: 'regular',
    applyDate: '2025-06-15',
    applyReason: '上次检验发现缺陷整改完成，申请复检',
    applicant: '吴十',
    applicantPhone: '13800138004',
    status: 'pending',
  },
  {
    applyNo: 'BJ202506006',
    companyId: companyIds[4],
    equipmentId: equipmentIds[6],
    inspectionType: 'periodic',
    inspectionNature: 'regular',
    applyDate: '2025-06-16',
    applyReason: '年度定期检验',
    applicant: '冯十二',
    applicantPhone: '13800138005',
    status: 'pending',
  },
];

const createSchedules = (applyIds: number[], companyIds: number[], equipmentIds: number[]): Omit<Schedule, 'id' | 'createdAt' | 'updatedAt'>[] => [
  {
    scheduleNo: 'PJ202506001',
    applyId: applyIds[0],
    companyId: companyIds[0],
    equipmentId: equipmentIds[0],
    inspectionType: '内部检验',
    planDate: '2025-06-10',
    planStartTime: '09:00',
    planEndTime: '17:00',
    actualDate: '2025-06-10',
    actualStartTime: '09:15',
    actualEndTime: '16:30',
    inspectorIds: '1,3',
    mainInspectorId: 1,
    inspectionLocation: '东方化工一号车间锅炉房',
    preparationItems: '设备已停炉冷却、内部通风、电源切断',
    status: 'completed',
    remark: '检验完成，发现2处一般缺陷',
  },
  {
    scheduleNo: 'PJ202506002',
    applyId: applyIds[1],
    companyId: companyIds[0],
    equipmentId: equipmentIds[1],
    inspectionType: '外部检验',
    planDate: '2025-06-20',
    planStartTime: '14:00',
    planEndTime: '17:00',
    inspectorIds: '2',
    mainInspectorId: 2,
    inspectionLocation: '东方化工办公楼地下室锅炉房',
    preparationItems: '设备正常运行，准备运行记录',
    status: 'scheduled',
  },
  {
    scheduleNo: 'PJ202506003',
    applyId: applyIds[2],
    companyId: companyIds[1],
    equipmentId: equipmentIds[2],
    inspectionType: '水压试验',
    planDate: '2025-06-25',
    planStartTime: '08:00',
    planEndTime: '16:00',
    inspectorIds: '1,2,4',
    mainInspectorId: 1,
    inspectionLocation: '华南制药制剂车间锅炉房',
    preparationItems: '准备试压泵、压力表、水',
    status: 'scheduled',
    remark: '需配合水压试验',
  },
  {
    scheduleNo: 'PJ202506004',
    applyId: applyIds[3],
    companyId: companyIds[2],
    equipmentId: equipmentIds[4],
    inspectionType: '专项检验',
    planDate: '2025-06-18',
    planStartTime: '09:00',
    planEndTime: '18:00',
    actualDate: '2025-06-18',
    actualStartTime: '09:00',
    inspectorIds: '1,3,4',
    mainInspectorId: 1,
    inspectionLocation: '北方钢铁炼钢车间',
    preparationItems: '重点检查过热器管排',
    status: 'in_progress',
    remark: '重点关注过热器材质劣化情况',
  },
  {
    scheduleNo: 'PJ202506005',
    applyId: applyIds[4],
    companyId: companyIds[3],
    equipmentId: equipmentIds[5],
    inspectionType: '复检',
    planDate: '2025-06-30',
    planStartTime: '09:00',
    planEndTime: '12:00',
    inspectorIds: '2,3',
    mainInspectorId: 2,
    inspectionLocation: '西湖食品蒸煮车间锅炉房',
    preparationItems: '已完成缺陷整改，准备整改记录',
    status: 'scheduled',
  },
];

const createHydroTests = (scheduleIds: number[], equipmentIds: number[]): Omit<HydroTest, 'id' | 'createdAt' | 'updatedAt'>[] => [
  {
    scheduleId: scheduleIds[0],
    equipmentId: equipmentIds[0],
    testDate: '2025-06-10',
    testMethod: '水压试验',
    testMedium: '清洁水',
    mediumTemperature: 25,
    testPressure: 1.56,
    pressureHoldingTime: 30,
    pressureDrop: 0.02,
    testEnvironment: '环境温度25℃，湿度65%',
    inspectionSituation: '对锅筒、水冷壁、集箱进行了全面检查',
    leakageSituation: '无渗漏',
    deformationSituation: '无可见变形',
    testResult: 'qualified',
    testerId: 1,
    witness: '东方化工设备科 王科长',
    remark: '试验压力为设计压力的1.25倍',
  },
  {
    scheduleId: scheduleIds[3],
    equipmentId: equipmentIds[4],
    testDate: '2025-06-18',
    testMethod: '水压试验',
    testMedium: '软化水',
    mediumTemperature: 30,
    testPressure: 5.0,
    pressureHoldingTime: 60,
    pressureDrop: 0.05,
    testEnvironment: '环境温度30℃',
    inspectionSituation: '对过热器、省煤器、汽包进行检查',
    leakageSituation: '过热器出口联箱有轻微渗漏',
    deformationSituation: '无明显变形',
    testResult: 'pending',
    testerId: 4,
    witness: '北方钢铁动力厂 李工',
    remark: '需要进一步检查渗漏点',
  },
];

const createValveTests = (scheduleIds: number[], equipmentIds: number[]): Omit<ValveTest, 'id' | 'createdAt' | 'updatedAt'>[] => [
  {
    scheduleId: scheduleIds[0],
    equipmentId: equipmentIds[0],
    valveName: '主蒸汽安全阀',
    valveModel: 'A48Y-16C',
    valveNo: 'V2024001',
    specification: 'DN100 PN16',
    manufacturer: '上海阀门厂',
    factoryDate: '2018-03-10',
    testDate: '2025-06-10',
    setPressure: 1.25,
    testPressure: 1.32,
    seatPressure: 1.18,
    backPressure: 0.1,
    testMedium: '饱和蒸汽',
    dischargeCapacity: 12.5,
    sealingPerformance: 'qualified',
    openingPressureDeviation: 0.01,
    testResult: 'qualified',
    adjustmentMethod: '调整弹簧预紧力',
    testerId: 1,
    nextTestDate: '2026-06-10',
    remark: '整定压力1.25MPa',
  },
  {
    scheduleId: scheduleIds[0],
    equipmentId: equipmentIds[0],
    valveName: '锅筒安全阀A',
    valveModel: 'A41H-16C',
    valveNo: 'V2024002',
    specification: 'DN80 PN16',
    manufacturer: '上海阀门厂',
    factoryDate: '2018-03-10',
    testDate: '2025-06-10',
    setPressure: 1.3,
    testPressure: 1.38,
    seatPressure: 1.22,
    testMedium: '饱和蒸汽',
    dischargeCapacity: 8.2,
    sealingPerformance: 'qualified',
    openingPressureDeviation: 0.015,
    testResult: 'qualified',
    testerId: 1,
    nextTestDate: '2026-06-10',
  },
  {
    scheduleId: scheduleIds[1],
    equipmentId: equipmentIds[1],
    valveName: '热水出口安全阀',
    valveModel: 'A47H-10C',
    valveNo: 'V2024003',
    specification: 'DN65 PN10',
    manufacturer: '浙江阀门有限公司',
    factoryDate: '2020-02-15',
    testDate: '2025-06-20',
    setPressure: 1.0,
    testPressure: 1.06,
    seatPressure: 0.94,
    testMedium: '热水',
    dischargeCapacity: 5.8,
    sealingPerformance: 'qualified',
    openingPressureDeviation: 0.008,
    testResult: 'pending',
    testerId: 2,
    nextTestDate: '2026-06-20',
  },
];

const createDefects = (scheduleIds: number[], equipmentIds: number[]): Omit<Defect, 'id' | 'createdAt' | 'updatedAt'>[] => [
  {
    scheduleId: scheduleIds[0],
    equipmentId: equipmentIds[0],
    defectNo: 'QX202506001',
    defectType: '腐蚀',
    defectLevel: 'general',
    defectLocation: '锅筒下部内壁',
    defectDescription: '发现局部点蚀，面积约0.5㎡，最大深度1.5mm',
    discoveryMethod: '目视检查 + 超声波测厚',
    discoveryDate: '2025-06-10',
    defectSize: 'Φ800mm',
    defectArea: 0.5,
    defectDepth: 1.5,
    causeAnalysis: '长期运行，水质控制不当导致电化学腐蚀',
    treatmentSuggestion: '进行打磨除锈，涂刷耐高温防腐涂料，加强水质管理',
    handlerId: 1,
    treatmentResult: '已完成打磨除锈和防腐处理',
    treatmentDate: '2025-06-15',
    recheckResult: '复查合格，腐蚀已消除',
    recheckDate: '2025-06-18',
    status: 'closed',
    remark: '下次检验重点关注该区域',
  },
  {
    scheduleId: scheduleIds[0],
    equipmentId: equipmentIds[0],
    defectNo: 'QX202506002',
    defectType: '焊缝缺陷',
    defectLevel: 'minor',
    defectLocation: '水冷壁管对接焊缝',
    defectDescription: '磁粉检测发现表面裂纹，长度约25mm',
    discoveryMethod: '磁粉检测(MT)',
    discoveryDate: '2025-06-10',
    defectSize: '长度25mm，深度2mm',
    defectDepth: 2,
    causeAnalysis: '焊接质量控制不严，产生表面热裂纹',
    treatmentSuggestion: '打磨清除裂纹，进行补焊，焊后热处理',
    handlerId: 3,
    treatmentResult: '已完成打磨补焊和热处理',
    treatmentDate: '2025-06-16',
    recheckResult: '磁粉复查合格，无缺陷显示',
    recheckDate: '2025-06-18',
    status: 'closed',
  },
  {
    scheduleId: scheduleIds[3],
    equipmentId: equipmentIds[4],
    defectNo: 'QX202506003',
    defectType: '材质劣化',
    defectLevel: 'major',
    defectLocation: '过热器高温段管排',
    defectDescription: '超声波检测发现管壁晶界氧化，球化等级3级',
    discoveryMethod: '超声波检测(UT) + 金相检验',
    discoveryDate: '2025-06-18',
    defectSize: '涉及12根管子',
    causeAnalysis: '长期高温运行，材质发生球化和石墨化',
    treatmentSuggestion: '立即更换该管排，缩短下次检验周期',
    handlerId: 4,
    status: 'processing',
    remark: '严重安全隐患，需尽快处理',
  },
  {
    scheduleId: scheduleIds[3],
    equipmentId: equipmentIds[4],
    defectNo: 'QX202506004',
    defectType: '泄漏',
    defectLevel: 'critical',
    defectLocation: '过热器出口联箱焊缝',
    defectDescription: '水压试验时发现焊缝泄漏，泄漏量约5L/min',
    discoveryMethod: '水压试验',
    discoveryDate: '2025-06-18',
    defectSize: '环向长度约150mm',
    causeAnalysis: '焊接应力未消除，运行中产生疲劳裂纹',
    treatmentSuggestion: '立即停炉，进行焊缝挖补和热处理，进行100%无损检测',
    handlerId: 1,
    status: 'pending',
    remark: '重大缺陷，必须立即处理',
  },
  {
    scheduleId: scheduleIds[4],
    equipmentId: equipmentIds[5],
    defectNo: 'QX202506005',
    defectType: '结垢',
    defectLevel: 'general',
    defectLocation: '锅筒内壁及受热面',
    defectDescription: '受热面结垢，平均厚度约3mm，主要为碳酸盐垢',
    discoveryMethod: '目视检查',
    discoveryDate: '2025-05-20',
    defectSize: '全受热面',
    defectDepth: 3,
    causeAnalysis: '水质处理不当，长期未进行化学清洗',
    treatmentSuggestion: '进行化学清洗，完善水处理系统，严格水质控制',
    handlerId: 2,
    treatmentResult: '已完成化学清洗，清洗效果良好',
    treatmentDate: '2025-06-10',
    status: 'rechecking',
    remark: '待复检确认清洗效果',
  },
];

const createReports = (applyIds: number[], scheduleIds: number[], companyIds: number[], equipmentIds: number[]): Omit<Report, 'id' | 'createdAt' | 'updatedAt'>[] => [
  {
    reportNo: 'BG202506001',
    applyId: applyIds[0],
    scheduleId: scheduleIds[0],
    companyId: companyIds[0],
    equipmentId: equipmentIds[0],
    inspectionType: '定期内部检验',
    inspectionBasis: '《锅炉定期检验规则》TSG G7001-2015',
    inspectionDate: '2025-06-10',
    inspectorIds: '1,3',
    mainInspectorId: 1,
    equipmentOverview: 'DZL10-1.25-AII型燃煤蒸汽锅炉，2018年8月投用，运行正常',
    inspectionItems: '资料审查、本体检查、安全附件检查、水压试验、无损检测',
    inspectionProcess: '按照检验方案进行了全面检验，包括宏观检查、测厚、MT、UT、水压试验等项目',
    defectList: '1. 锅筒下部内壁点蚀，已处理；2. 水冷壁焊缝表面裂纹，已修复',
    hydroTestId: 1,
    valveTestIds: '1,2',
    overallResult: 'qualified',
    handlingOpinion: '检验合格，同意继续使用，下次检验日期为2026年8月',
    nextInspectionDate: '2026-08-10',
    reportEditorId: 1,
    reportEditorDate: '2025-06-20',
    reviewerId: 5,
    reviewerOpinion: '资料齐全，检验项目完整，结论准确',
    reviewDate: '2025-06-22',
    approverId: 5,
    approverOpinion: '同意出具检验报告',
    approvalDate: '2025-06-23',
    status: 'issued',
    issueDate: '2025-06-23',
  },
  {
    reportNo: 'BG202506002',
    applyId: applyIds[3],
    scheduleId: scheduleIds[3],
    companyId: companyIds[2],
    equipmentId: equipmentIds[4],
    inspectionType: '专项监督检验',
    inspectionBasis: '《锅炉监督检验规则》TSG G7001-2015',
    inspectionDate: '2025-06-18',
    inspectorIds: '1,3,4',
    mainInspectorId: 1,
    equipmentOverview: 'QC60/450-20-4.0型余热锅炉，2019年12月投用，近期发现过热器超温',
    inspectionItems: '过热器专项检查、材质分析、水压试验、金相检验',
    inspectionProcess: '针对过热器进行专项检验，发现材质劣化和泄漏缺陷',
    defectList: '1. 过热器管排材质球化3级；2. 过热器出口联箱焊缝泄漏',
    hydroTestId: 2,
    valveTestIds: '',
    overallResult: 'unqualified',
    handlingOpinion: '存在重大安全隐患，必须立即停炉整改，整改完成后申请复检',
    nextInspectionDate: '2025-12-18',
    reportEditorId: 4,
    reportEditorDate: '2025-06-19',
    reviewerId: 5,
    reviewerOpinion: '检验情况属实，缺陷定性准确',
    reviewDate: '2025-06-19',
    status: 'reviewing',
    remark: '重大问题，需尽快出具正式报告',
  },
  {
    reportNo: 'BG202506003',
    applyId: applyIds[4],
    scheduleId: scheduleIds[4],
    companyId: companyIds[3],
    equipmentId: equipmentIds[5],
    inspectionType: '复检',
    inspectionBasis: '《锅炉定期检验规则》TSG G7001-2015',
    inspectionDate: '2025-06-30',
    inspectorIds: '2,3',
    mainInspectorId: 2,
    equipmentOverview: 'WNS6-1.25-Y型燃油蒸汽锅炉，2017年6月投用，上次检验发现结垢缺陷',
    inspectionItems: '结垢整改情况复查、内部宏观检查',
    inspectionProcess: '对上次检验发现的结垢缺陷整改情况进行复查',
    overallResult: 'conditional_qualified',
    handlingOpinion: '整改基本到位，但仍需加强水质管理，3个月后再次复查',
    nextInspectionDate: '2026-06-30',
    reportEditorId: 2,
    reportEditorDate: '2025-06-30',
    status: 'draft',
  },
];

const createCertificates = (reportIds: number[], companyIds: number[], equipmentIds: number[]): Omit<Certificate, 'id' | 'createdAt' | 'updatedAt'>[] => [
  {
    certificateNo: 'ZY202506001',
    reportId: reportIds[0],
    companyId: companyIds[0],
    equipmentId: equipmentIds[0],
    certificateType: 'inspection',
    issueDate: '2025-06-23',
    validFrom: '2025-06-23',
    validTo: '2026-06-22',
    issuingAuthority: '北京市特种设备检验研究院',
    issuer: '李安全',
    inspectionConclusion: '按照《锅炉定期检验规则》进行检验，结论为合格',
    equipmentInfo: 'DZL10-1.25-AII 燃煤蒸汽锅炉，设备编号GL-2024-0001',
    remarks: '下次检验日期2026年8月10日前',
    status: 'valid',
    printCount: 2,
    lastPrintDate: '2025-06-24',
  },
  {
    certificateNo: 'ZY202506002',
    reportId: reportIds[0],
    companyId: companyIds[0],
    equipmentId: equipmentIds[0],
    certificateType: 'use_registration',
    issueDate: '2025-06-25',
    validFrom: '2025-06-25',
    validTo: '2027-06-24',
    issuingAuthority: '北京市朝阳区市场监督管理局',
    issuer: '张登记',
    inspectionConclusion: '检验合格，准予登记使用',
    equipmentInfo: 'DZL10-1.25-AII 燃煤蒸汽锅炉，使用登记证号锅京朝字第0001号',
    status: 'valid',
    printCount: 1,
  },
  {
    certificateNo: 'ZY202506003',
    reportId: reportIds[2],
    companyId: companyIds[3],
    equipmentId: equipmentIds[5],
    certificateType: 'inspection',
    issueDate: '2025-06-30',
    validFrom: '2025-06-30',
    validTo: '2026-06-29',
    issuingAuthority: '浙江省特种设备检验研究院',
    issuer: '李安全',
    inspectionConclusion: '复检合格，整改措施有效',
    equipmentInfo: 'WNS6-1.25-Y 燃油蒸汽锅炉，设备编号GL-2024-0006',
    remarks: '3个月后需进行水质专项检查',
    status: 'valid',
    printCount: 0,
  },
];

export async function seedDatabase(dbPath?: string): Promise<void> {
  if (dbPath) {
    await dbManager.initForTest(dbPath);
  } else {
    await dbManager.init();
  }

  const existingCompanies = dbManager.count('company');
  if (existingCompanies > 0) {
    console.log('Database already has data, skipping seed.');
    return;
  }

  dbManager.transaction(() => {
    const companyIds = dbManager.insertMany('company', companies);
    console.log(`Inserted ${companyIds.length} companies`);

    const inspectorIds = dbManager.insertMany('inspector', inspectors);
    console.log(`Inserted ${inspectorIds.length} inspectors`);

    const equipments = createEquipments(companyIds);
    const equipmentIds = dbManager.insertMany('equipment', equipments);
    console.log(`Inserted ${equipmentIds.length} equipments`);

    const applies = createInspectionApplies(companyIds, equipmentIds);
    const applyIds = dbManager.insertMany('inspection_apply', applies);
    console.log(`Inserted ${applyIds.length} inspection applies`);

    const schedules = createSchedules(applyIds, companyIds, equipmentIds);
    const scheduleIds = dbManager.insertMany('schedule', schedules);
    console.log(`Inserted ${scheduleIds.length} schedules`);

    const hydroTests = createHydroTests(scheduleIds, equipmentIds);
    const hydroTestIds = dbManager.insertMany('hydro_test', hydroTests);
    console.log(`Inserted ${hydroTestIds.length} hydro tests`);

    const valveTests = createValveTests(scheduleIds, equipmentIds);
    const valveTestIds = dbManager.insertMany('valve_test', valveTests);
    console.log(`Inserted ${valveTestIds.length} valve tests`);

    const defects = createDefects(scheduleIds, equipmentIds);
    const defectIds = dbManager.insertMany('defect', defects);
    console.log(`Inserted ${defectIds.length} defects`);

    const reports = createReports(applyIds, scheduleIds, companyIds, equipmentIds);
    const reportIds = dbManager.insertMany('report', reports);
    console.log(`Inserted ${reportIds.length} reports`);

    const certificates = createCertificates(reportIds, companyIds, equipmentIds);
    const certificateIds = dbManager.insertMany('certificate', certificates);
    console.log(`Inserted ${certificateIds.length} certificates`);
  });

  console.log('Database seeding completed successfully!');
}

export function clearDatabase(): void {
  dbManager.transaction(() => {
    dbManager.deleteByCondition('certificate', {});
    dbManager.deleteByCondition('report', {});
    dbManager.deleteByCondition('defect', {});
    dbManager.deleteByCondition('valve_test', {});
    dbManager.deleteByCondition('hydro_test', {});
    dbManager.deleteByCondition('schedule', {});
    dbManager.deleteByCondition('inspection_apply', {});
    dbManager.deleteByCondition('equipment', {});
    dbManager.deleteByCondition('inspector', {});
    dbManager.deleteByCondition('company', {});
  });
  console.log('Database cleared successfully!');
}

export default { seedDatabase, clearDatabase };
